### ISSUE TITLE
CAGR: Flawed calculation?

### ISSUE THREAD

**Issue by Alexander-Shukaev** [dcajasn/Riskfolio-Lib#104]
It appears to me that employed CAGR calculations are flawed:

https://github.com/dcajasn/Riskfolio-Lib/blob/af55dc242baf8e294c66f6ff662b175ce2227922/riskfolio/PlotFunctions.py#L1790
https://github.com/dcajasn/Riskfolio-Lib/blob/af55dc242baf8e294c66f6ff662b175ce2227922/examples/Tutorial%2017.ipynb?short_path=a1fdd9d#L778

Let me try to illustrate my point with a toy example.  Imagine we have a portfolio of 2 assets, where each has equal weight (0.5).  Now let's say that we only look at 2 days of returns, where on the first day 1st asset gave 50% return and 2nd asset gave 0% return, while on the second day 1st asset gave 0% return and 2nd asset gave 50% return.  Pretty simple, isn't it?  Let's now run through a simple example with actual cash numbers: say we allocated 100$ to each, then in the beginning we have 200$ total, then after the first day close we have 150$ and 100$ respectively (250$ in total), while after the second day close we have 150$ and 150$ respectively (300$ in total).  This clearly give us 50% total return (from 200$ to 300$) on the whole portfolio after these 2 days.

Having this example in mind, let's run through the formulas used in the above code snippets:

```
          returns        w
| 1 | + | 0.5 0   | * | 0.5 | = | 1.25 |
| 1 |   | 0   0.5 |   | 0.5 |   | 1.25 |
```

and then the whole portfolio CAGR after these 2 days becomes 56.25% as per

```
1.25 * 1.25 - 1 = 0.5625
```

which is obviously way off the actual 50% total return illustrated above.

Dropping intuition and thinking physically about this, I guess the explanation is that each asset return (price) moves independently (from each other) and you cannot mix them with portfolio weights in the first stage of calculation because then you essentially compound weighted daily returns of independent assets (as if it was one asset), which is physically incorrect.  Instead, each asset compounds independently from day to day.  So we should rather calculate CAGR for each asset independently and only then perform inner product of this resulting vector of asset CAGRs with weights to get the whole portfolio CAGR:

```
1.5 * 1 - 1 = 0.5
1 * 1.5 - 1 = 0.5
0.5 * 0.5 + 0.5 * 0.5 = 0.5
```

**Comment by dcajasn** [comment]
Hi @Alexander-Shukaev,

The CAGR calculation is fine because the assumption is daily rebalancing with no transaction costs. In your example your assumption is buy and hold. We use these assumptions to ilustrate the behavior of this specific asset allocation because when you make buy and hold, your asset allocation change each day. Also, this function is just informative, for more real calculation is better to use a backtesting library like the examples in documentation.

Best,
Dany

**Comment by Alexander-Shukaev** [comment]
@dcajasn, Oh, right, I see what you mean.  I didn't think even about it this way, perhaps because re-balancing on each daily close sounds unrealistic and inefficient for real life.  But sure, for idealistic modeling purposes makes total sense.  Also agree on back testing part.  Thanks for the explanation.

By the way, regarding testing and evaluation in general.  The issue that I see with CAGR, or Sharpe ratio, and any other "static" metrics is that they are numbers from the hindsight kind of.  That is if we use weights that were computed from historical data, and apply those weights to calculate these metrics on that historical data, then we're kind of fooling ourselves by using information from the "future" essentially to build a portfolio in the past, which is nonsense.  What are typical recommendations/approaches to eliminate this?  I can imagine two:

1.  During back testing, actually take chunks of historical data between re-balancing interval boundaries and use them as historical input to the model to obtain weights, and then use these weights until the next re-balancing, while for the next period, use that previous period and the one before as historical input to the model to obtain next set of weights.  This is actually how this whole portfolio management would be applied in reality, but just simulating it on historical data.  Is this what is referred to as "forward testing"?
2.  Heard about methods where some kind of Monte Carlo simulated modifications are applied to historical data to introduce some random additional noise and features in order to test other unexpected scenarios.  Is this what is referred to as "forward testing"?

Apart from the two tutorials, are there any other good sources on this that you could recommend?  Thanks a lot for your time.

**Comment by dcajasn** [comment]
Hi @Alexander-Shukaev,

I agree with you about "static" metrics, but I use that kind of metrics in Riskfolio-Lib reports because portfolio optimization models are based on them and I want that users see the same metrics used in the optimization process. I designed Riskfolio-Lib for single period portfolio optimization.

About your proposed solutions, I prefer backtesting using "historical data" and "block boostrapping" using the rolling window approach. I don't like montecarlo too much because you need to assume a distribution, doesn't work well with drawdown risk measures and it is difficult to model autocorrelation.

About tutorials, well I don't know more tutorials on multi asset backtesting, I made both tutorials reading the libraries documentation.

Best,
Dany
