### ISSUE TITLE
CAGR calc in PlotFunctions.py

### ISSUE THREAD

**Issue by uhasan1** [dcajasn/Riskfolio-Lib#16]
https://github.com/dcajasn/Riskfolio-Lib/blob/0fd1d8c21ad86bcb88a9b0bc9b986aa213fadfcb/riskfolio/PlotFunctions.py#L1373
https://github.com/dcajasn/Riskfolio-Lib/blob/0fd1d8c21ad86bcb88a9b0bc9b986aa213fadfcb/riskfolio/PlotFunctions.py#L1413

Hi - quick question with CAGR -- having trouble reproducing your number and wanted to ask if your comfortable with the consistency of ini_days usage. More specifically, where use monthly data, returns index is month end dates and ini_days set to 21 based on 252 days per year, a) is this CAGR calculation ok with the 360 hardcode in line 1413, and b) days calculation ok in 1373?

btw, thanks again for your lovely and very generous contribution with this library.

**Comment by dcajasn** [comment]
Hi @uhasan1,

Thanks for communicate me the inconsistencies in the code. I forgot to update that part in plotfunctions when I added the variable ini_days, I will add a new variable for days per year to fix that part in the new version. In general, I'm more worried on errors on the portfolio module because it is the core of the project, so I really appreciate when people help me to find errors on other modules. I hope I will fix that error on the following days.

**Comment by dcajasn** [comment]
Hi @uhasan1,

I've just uploaded the new version with the solution of the errors you mentioned above.

Best
Dany
