### ISSUE TITLE
Tracking error

### ISSUE THREAD

**Issue by TomLiu518** [dcajasn/Riskfolio-Lib#2]
Hi Dany, I am looking for solution for incorporate tracking error as a constraint. In your examples in Tutorial 7 I failed to find out how you incorporate an index. The results are not likely to be correct because you have zero weights on several stocks APA, BMY, HPQ, etc, which is not really possible if you want to track certain index. 
Furthermore, how do you calculate tracking error in your codes? is it ex-post: so the standard deviation of historical returns x relative weight , where relative weight = portfolio weights - benchmark weights, or is it ex-ante: so transpose(relative weights)@variance_covirance@relative weights?

**Comment by dcajasn** [comment]
Hi Tom, the formula that I use for tracking error is to calculate the difference between the index returns and portfolio returns and then calculate the sample standard deviation of this difference. I use this approach that is equivalent to the ex-ante because it can be used when you don't have the composition of assets of an index. Also, the tracking error is a constraint, so the resulting portfolio must have a tracking error lower or equal than your constraint. Another problem that you must consider is that the tracking error constraint must be in the same frequency than your assets returns. If you have a problem, you can send me your notebook to check where is your problem.

**Comment by TomLiu518** [comment]
Hi Dany, thanks. I guess my question now is, can you customize constraint and objective functions? for example if i want use a different method to calculate tracking error as a constraint?

**Comment by dcajasn** [comment]
Hi Tom, about your question you can't customize objective functions. The reason for this is that Riskfolio-Lib is based on cvxpy so it can only solve disciplined convex problems. All combinations of objective functions and constraints in Riskfolio-Lib are disciplined convex problems (you can check the papers in documentation), so they can be solved by cvxpy. On the other hand, if you want to limit the max value of a risk measure while optimize another is posible (I will make an example soon), for example you can maximize sharpe ratio while you put a constraint on CVaR. Finally, If you want a new objective function or constraint, check if they are convex and send me the formula or paper is based to try to include in Riskfolio-Lib.
