### ISSUE TITLE
Question about the two_diff_gap_stat function

### ISSUE THREAD

**Issue by alfiannajih** [dcajasn/Riskfolio-Lib#202]
Hi there,

I have question regarding the implementation of two_diff_gap_stat function, so the paper state the optimal number of clusters is a `c` that maximize the set of gaps:
![image](https://github.com/user-attachments/assets/f902d9e9-a47a-4130-a768-329631a8c08f)
and I looked the corresponding code:
```
...
gaps = W_list.shift(2) + W_list - 2 * W_list.shift(1)
gaps = gaps[0:limit_k]
if gaps.isna().all():
    k = len(gaps)
else:
    k = int(gaps.idxmax() + 2)
...
```

when I try it, it gave me a list of gap with the first two index is a NaN e.g. `[NaN, NaN, gap_1, gap_2, ...]`, should the list shift to the left first so the gaps is `[gap_1, gap_2, ....]`, and then perform the idxmax() to it? Also in the end of the code, why added 2 to the gaps.idxmax()? I assume the minimum cluster should be 2 so it added 2 by the end?

**Comment by dcajasn** [comment]
Hi @alfiannajih 

I did that code in 2021, so I don't remember well but the idea is that instead of use a forward approximation of second difference, I use a [backward approximation of second difference](https://en.wikipedia.org/wiki/Finite_difference) to avoid the cases with one and two clusters. The +2 is to fix the backward approximation and that indexes in Python starts in 0.

Best,
Dany

**Comment by dcajasn** [comment]
Hi @alfiannajih,

I fixed the code to use the same version of the original paper of two difference gap statistic. Also, I fixed it for nonmonotonic linkage matrices (centroid and median linkage). Download version 6.2.2.

Best,
Dany
