### ISSUE TITLE
【HCPortfolio.py】Why do np.power in MV, This seems to cause RP anomalies

### ISSUE THREAD

**Issue by quanxiang-liu** [dcajasn/Riskfolio-Lib#207]
Firstly, thank you very much for your open source contribution, I have questions about the HCPortfolio.py file

At https://github.com/dcajasn/Riskfolio-Lib/blob/master/riskfolio/src/HCPortfolio.py#L402 and https://github.com/dcajasn/Riskfolio-Lib/blob/master/riskfolio/src/HCPortfolio.py#L196 I see that you made inv_risk = 1 / np.power(inv_risk, 2 )

I'm guessing the reason for this might be that np.sqrt(risk.item()) is done first here at https://github.com/dcajasn/Riskfolio-Lib/blob/master/riskfolio/src/RiskFunctions.py#L1843 

But the above two np.sqrt and then np.power will cause the cluster can not reach the RP, I try any other rm function except MV, can get the correct result, as shown in the figure below, only MV returns the asset allocation weight and other rm function is very different, I try to change to “inv_risk = 1 / inv_risk” can get more reasonable results!

Before modification：
<img width="1020" alt="image" src="https://github.com/user-attachments/assets/05eb90b9-998a-4b16-9753-e60c093145e3">
After：
<img width="1016" alt="image" src="https://github.com/user-attachments/assets/36705840-87a7-4c7e-afd8-2d0c220c9bdd">

Thanks again for your open source, it helped me a lot!

**Comment by dcajasn** [comment]
Hi @quanxiang-liu,

This is not an issue. Sharpe_risk function takes sqrt because is designed to calculate the risk associated to mean-variance model, but in practice instead of use variance practitioners and academics use standard deviation. In HCPortfolio we use the power because it reproduces the results of HRP paper, please read papers before raise and issue. The case without the power is obtained when you use the 'vol' parameter.

Best,
Dany
