### ISSUE TITLE
Custom risk measure function for HERC method

### ISSUE THREAD

**Issue by arthurire** [dcajasn/Riskfolio-Lib#43]
Hi Dany,

Thank you for providing us such an amazing library, I really appreciate it.

I would be grateful if you could provide support for custom risk measure for HERC method [here](https://riskfolio-lib.readthedocs.io/en/latest/_modules/HCPortfolio.html#HCPortfolio). 

I would like to 

Best regards,

**Comment by dcajasn** [comment]
Hi @arthurire ,

All hierarchical clustering portfolio models implemented in Riskfolio-Lib have the option to use custom covariance. There is an example that shows how to use custom covariance matrix.

Best,
Dany

**Comment by arthurire** [comment]
> 

Okay got it. I will try to implement custom risk measure, if possible.

**Comment by arthurire** [comment]
Hi Dany,

Thank you for your reply.

My original intention was to define custom risk measure like what you did to custom covariance. However, I have not read all the code, so I am more worried that my own modification and merge will produce errors. I am very willing to develop this function, if you do not have this plan now.

Best,
Arthur

**Comment by dcajasn** [comment]
Well, I implemented custom covariance because it is a special case for the following reasons:

- There are several ways to estimate covariance matrix like historical, ewma, ledoit and wolf, oracle, risk factor models, black litterman, etc. Even the techniques can be combinated for example using ledoit and wolf on ewma covariance.
- A custom covariance not only affects portfolio variance, also affects the hierarchical structure used to calculate the weights in all clustering portfolio models.

**Comment by arthurire** [comment]
I took a rough look at the code, and there is a big difference between your implementation of covariance and the implementation of risk measure, which I didn't expect at the beginning.

For me, I need to calculate two-sided risk. For myself, the simpler method is to clone your code and change some kind of risk, such as AvgDrawDown, to calculate the two-sided risks.

However, I don't think this kind of monkey patch is a long-term solution, that's the reason why I open this issue and hope if we could discuss about it.

In order to ensure that I can express my thoughts more clearly, please allow me to give an example.AvgDrawDown only calculates the drawdown when I have long positions. If I short an equity, then the profit of long positions becomes the risk that short positions need to avoid, so I need to calculate the two-sided risk.

**Comment by arthurire** [comment]
I will first try to inherit your add function and design a two_sided_add to see if it works.

**Comment by dcajasn** [comment]
About your concerns:

- Riskfolio-Lib doesn't allow short positions in hierarchical clustering portfolio models. I saw that feature in Mlfinlab and Portfoliolab but their implementation is not practical because you need to define in advance which assets you are going to short.
- About drawdown functions, in the case short positions are allowed, the factor -1 should be multiplicated to the returns before drawdowns functions be calculated, however it's not clear if this should impact the hierarchical structure. In general, hierarchical clustering portfolio models are designed for long only portfolios.

**Comment by arthurire** [comment]
Currently I'm using `abs_pearson` as correlation measure and `vol` as risk measure. But `vol` does not reflect the tail risk.

**Comment by dcajasn** [comment]
> I have seen mlfinlab's implementation on this problem, and I have more thoughts about it.
> 
> I do not expect to define the long and short positions when allocating risk. I hope if I could design a risk measure, under which the risk exposure of Long A Short B, and Long A Long B are identically the same.
> 
> Therefore, I consider using the `abs_pearson` method and two-sided risk measure.
> 
> There is no strict proof, but I think this is feasible.
 
It seems that you are not looking for a risk measure, you are looking for a codependence measure. About tail risk, there are several risk measures available in Riskfolio-Lib that reflects tail risk like CVaR, EVaR, Worst case.

**Comment by arthurire** [comment]
Indeed. Through this discussion I found that what I am calculating is not the actual risk exposure, but some kind of co-dependence.
Thank you for answering my question, I will close this issue.
