### ISSUE TITLE
LPM function results 

### ISSUE THREAD

**Issue by wapebira** [dcajasn/Riskfolio-Lib#6]
https://www.mathworks.com/help/finance/lpm.html
While FLPM looks ok, the LPM function does not give the same results for ZLPM. SLPM, TLPM as MATLAB.

**Comment by dcajasn** [comment]
Hi @wapebira, I check your problem, the Riskfolio-Lib LPM function was designed for orders p>= 1, for this reason you have an error for ZLPM. In the case of Higher LPM (HLPM, p > 1), I divide the sum of p-powers by n-1, because we are calculating sample HLPM. If you multiply the Riskfolio-Lib HLPM by np.power(n-1 / n, 1/p) I think you will get the same HLPM than MATLAB, try this adjustment and tell me if works. On the other hand, I will adjust the formula for ZLPM this week. Finally, if you still have problems write me.

**Comment by wapebira** [comment]
@dcajasn 
From my PoV, your interpretation is not correct
https://www.researchgate.net/publication/2382526_A_Brief_History_of_Downside_Risk_Measures

First, your sum includes also the values above the threshold. And they should be 0.
![image](https://user-images.githubusercontent.com/33706212/103785191-ea8cf980-5008-11eb-92a9-c82a96312083.png)

Second, all the other implementations I could find do not use n-1. Probably because we already assume the data we analyse it is a sample anyway, rather than an entire population?

This is the way I did it.

```
    def lpm(R, t, a):
        # Get the max between 0 and SVt (t-Ri)
        d = np.add(-R, t)
        d = d.clip(min=0)
        d = np.where(d == 0, d, pow(d, a)).sum()
        return d / len(R)
```

r: the returns array
t: the threshold
a: the LPM order

These are the results compared to MATLAB. The small differences are because of different weights being generated during optimization in Python and MATLAB.
![image](https://user-images.githubusercontent.com/33706212/103794154-6475b080-5012-11eb-90d0-c65ec6e44abf.png)
![image](https://user-images.githubusercontent.com/33706212/103794213-72c3cc80-5012-11eb-89dd-d1658b056040.png)

**Comment by dcajasn** [comment]
Hi @wapebira I understand your PoV, however the formula in the paper are population estimators and if you apply directly the formula to your sample with a>1 you will get a biased estimator of LPM. If you want an unbiased estimator of LPM you need to adjust the formula for higher central moments. You can check these links [Some Estimation Problems Related to a Geometric Distribution and the Sum of Two Independent Nonidentically Distributed Random Variables - page 5](https://statistics.stanford.edu/sites/g/files/sbiybj6031/f/SOL%20ONR%20130.pdf) and [Computer algebra and algorithms for unbiased moment estimation of arbitrary order](https://www.tandfonline.com/doi/full/10.1080/25742558.2019.1701917). For a = 2, 3, 4, the adjustments to make unbiased the sample estimators of central moments are:

![image](https://user-images.githubusercontent.com/61527316/103811452-f12c6880-502a-11eb-94b1-0242ae202908.png)

You can see, that the factor n/(n-1) reduce the bias of the estimators in the 4 cases. Also there is a R package called [Umoments R package](https://cran.r-project.org/web/packages/Umoments/index.html) that allows to estimate unbiased central moments.

Finally, the formula LPM that I developed for Riskfolio-Lib was mainly thought for first and second LPM, because they are related with the problems of maximization of Omega and Sortino ratio.

If you have more doubts please write me.
