### ISSUE TITLE
Example for using market caps

### ISSUE THREAD

**Issue by cryptocoinserver** [dcajasn/Riskfolio-Lib#64]
Once again thank you for this incredible library. 

Is there an example or could you provide one regarding how to use BlackLitterman with market caps.

Like it's explained here: [https://pyportfolioopt.readthedocs.io/en/latest/BlackLitterman.html#priors](https://pyportfolioopt.readthedocs.io/en/latest/BlackLitterman.html#priors)

I have a dataframe with daily market caps for each asset.

**Comment by dcajasn** [comment]
Hi @cryptocoinserver,

Just use the market caps, there is a parameter for custom equilibrium weights.

Best,
Dany

**Comment by cryptocoinserver** [comment]
Thanks for the fast reply, did a search in the docs, but still don't understand it.

If I understand it right I need to create a view to get P & Q for blacklitterman_stats:
`P, Q = rp.assets_views(views, asset_classes)`

```
asset_classes = {'Assets': ['JCI','TGT','CMCSA'], 
                 'Market Cap': [1234, 5678, 91011]}

asset_classes = pd.DataFrame(asset_classes)
asset_classes = asset_classes.sort_values(by=['Assets'])
```
Then from that create the view?

Could you post a simple example / scratch I can work with? 

Sent you a little appreciation with ko-fi for your time.
Thank you.

**Comment by dcajasn** [comment]
Hi @cryptocoinserver,

I don't plan to build an example about that because the documentation is very clear about how to use the Black-Litterman model. About the views you are creating, it seems that you don't understand well the Black-Litterman model, I recommend you to read the original paper http://www.jstor.org/stable/4479577 and this paper https://doi.org/10.2139/ssrn.1314585 that resumes well Black-Litterman model.

Best,
Dany

**Comment by cryptocoinserver** [comment]
Yeah that's probably the reason. Thank you for your suggestion.
I will give it a try and hopefully figure it out. 

Nevertheless, thank you for your time.

**Comment by cryptocoinserver** [comment]
Just reporting back. Got a better understanding of black litterman. Thank you for that. As a beginner starting to experiment / learn portfolio optimization I'm still overwhelmed with the complexity / many possibilities of riskfolio though.  No idea to be honest how to do it even with your hints (custom equilibrium weights). I will give PyPortfolioOpt a try for now. Seems to be less powerful, but more beginner-friendly, maybe I manage to do it there.

If by any chance someone else familiar with riskfolio, who has the time and joy in helping a beginner, reads this and knows how to do it, I would be very grateful for a short example.

**Comment by dcajasn** [comment]
Sure, Pyportfolioopt is more beginer friendly. But as an advice, Portfolio optimization requires a good level on mathemathics because it uses convex optimization, econometrics, statistics, machine learning, etc. Remember Zillow's case, people that only relies in libraries (FacebookProphet) without knowing the mathematics behind can lose a lot of money.
