### ISSUE TITLE
Architecture issues

### ISSUE THREAD

**Issue by JettroCode** [dcajasn/Riskfolio-Lib#66]
Hi Dany.

At first Im want to thanks you a lot, its awesome and very careful project. Examples are very useful too.

Im finded some architectural issues in Riskfolio:

- Function plot_frontier contains some calculation logic, which must been in a class method efficient_frontier, how it seems to me
- Risk measures props (measurement name, etc.) are smeared on code - in if statements and etc. Could it be collect risk measures props in dict or class, from which another classes might inharit props, or it can be a config file for example.

Im beginner on Py, its explaining why Im doing all for a long time, but I can try doing that changes and pull it in repo.

**Comment by dcajasn** [comment]
Hi @JettroCode,

Thanks for use Riskfolio-Lib. About your comments:

- I put the calculations in plot_frontier because they increase time to calculate efficient frontier and is a waste of memory save that calculations on portfolio object. On the other hand, efficient_frontier is just informative and it is designed for educational proposes, it is not recommendable to use  efficient_frontier for large number of assets when risk measure is different from variance.
- The if statements are required because risk measures have different properties. 

Best,
Dany

**Comment by JettroCode** [comment]
Hi @dcajasn 

Thanks for your answer.
