### ISSUE TITLE
Feature Request: Annualized Returns (CAGR)

### ISSUE THREAD

**Issue by jkleint** [dcajasn/Riskfolio-Lib#7]
Thanks for such a great library!  I especially like the new tearsheet reports.  Would it be possible to report annualized returns (and standard deviations), since that's what most people are familiar with, and what most other tools / services use?  I'm thinking specifically on the report and on efficient frontier plots.  Thanks!

**Comment by dcajasn** [comment]
Hi, thanks for your support. I'm planning to show annualized indicators for efficient frontier plot, tables and excel report; however I'm not sure about what assumption to use:

- For annualized returns, I have doubts between arithmetic or geometric returns and day-count convention. Maybe I could put an option to choose the convention and the type of annualized return, but I prefer arithmetic over geometric, because geometric increase too much the values when we work with daily data.
- For risk measures, in the case of std. dev. is easy because I only need to multiply by a factor depending on day-count convention; however in the case of other risk measures I'm not sure how to annualize them, for example MAD is similar than std. dev. but is a linear risk measure and if I use a linear, annual MAD becomes too big; EVaR, CVaR, FLPM, Worst Realization are also linear but became to big if I use a linear factor. If you have a paper about how to annualize them, a technical report, excel, a library or an idea of how to do it, please share that information and I implement that features ASAP. Meanwhile, I'm investigating by myself.

Now, I'm repairing some small bugs, making an example of how to use riskfolio-lib with MOSEK (for large scale programs), an example of backtesting using [vectorbt](https://github.com/polakowo/vectorbt), and I planning to add the technique [Near Optimal Centering](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3572435) for robust optimization.

Finally, please share the library with your friends or colleagues, because with more people who use it, it will help me to improve it.

**Comment by jkleint** [comment]
Awesome.  Geometric returns are pretty ubiquitous, and 252 trading days per year is the standard in the U.S., but I totally agree they should be configurable.  Only annualizing the stddev is fine, it's by far the most common risk measure; probably not worth worrying about the others.  Thanks!

**Comment by dcajasn** [comment]
Hi @jkleint, I just release the version 0.1.1 with the option to annualize the returns and risk in frontier plot, Jupyter notebook and Excel Reports. If you think this solution is right please close the issue.
