### ISSUE TITLE
What the k variable and 1000 for ?

### ISSUE THREAD

**Issue by lemon234071** [dcajasn/Riskfolio-Lib#74]
When the objective is "sharpe" i see some constraints multiply variable k and 1000, what are these options for ???
For example 
constraints += [mu @ w - rf0 * k == 1]
objective = cv.Minimize(risk * 1000)

Thank you

**Comment by dcajasn** [comment]
Hi @lemon234071,

This is a channel to reports errors, not a channel to learn mathematics or programming. All papers are available in documentation, and you can experiment with the code in your machine. So please, don't raise an issue for things that you can learn by yourself.

Best,
Dany

**Comment by lemon234071** [comment]
Maybe you are right, and I searched it in cvxpy doc and riskfolio doc, maybe i am just not smart enough, you can just ignore the issue,  please don't use a sarcastic tone. I don't think you have the right to discriminate against people who are dumber than you in some unfamiliar aspects.

**Comment by dcajasn** [comment]
I'm not being sarcastic. I only told you that first experiment in your machine, this is how I learned to programming. If I give you the quick answer is likely that you forget it in some weeks but if you experiment and discover the reason you will remember this forever.

**Comment by lemon234071** [comment]
Please stop quibbling. You don't know if I searched it. I have been programming for many years, thank you for teaching me how to learn such an advanced knowledge point “*1000”, and I really only saw it in your repo. You know what？ When you have more than 1k stars repository, you can't avoid issues, just be patient.

**Comment by dcajasn** [comment]
Sorry if you feel offended, but this is not an issue, it is a question. About "*1000" is just to increase the precision of solution. Returns are like 0.01% (0.001) and covariance are returns squared (0.000001), so some solvers have problems when you try to solve some portfolio models, specially when you use fractional programming. So to solve this problem I multiply some constraints and the objective function to increase the precision of the solution. And it is 1000, not 10, 100 or 10000 because after several experiments it is the value that don't give errors an give better precision in results. Also to compare precision you can calculate risk/return ratio with and without "*1000". Other packages multiply returns by 100 to increase precision but this modify the solution in some cases, specially when you use utility functions as objective (returns is linear and variance quadratic).

**Comment by lemon234071** [comment]
Thank you for your reply.
