### ISSUE TITLE
jupyter_report returns parameter

### ISSUE THREAD

**Issue by hale4029** [dcajasn/Riskfolio-Lib#96]
Hi Dany - I think we should consider including two return parameters for [`jupyter_report`](https://riskfolio-lib.readthedocs.io/en/latest/_modules/Reports.html#jupyter_report). One for simple returns and another for log returns. Or state that the function is best suited for log returns. The function immediately calculates cumulative returns by using `cumsum`, which makes a large assumption that the user knows to use log returns when the examples on the website tend to use simple returns.

**Comment by dcajasn** [comment]
Hi @hale4029, Riskfolio-Lib doesn't make any assumption about returns, you can use a returns matrix based on logarithmic or arithmetic returns with daily, weekly, annual or custom frequency. jupyter_reports uses the formula of uncompounded returns for drawdowns because portfolio models that optimize a risk measure based on drawdowns only can be posed as a dcp problems for uncompounded returns. The idea is that this value is equal to drawdown risk measure optimized by Riskfolio-Lib, and you can use it as reference if you want to put a constraint on a drawdown risk measure. As a reference you can see the Uryasev paper "portfolio optimization with drawdown constraints"
